const CartActionTypes = {
  CHANGE_CURRENCY: "CHANGE_CURRENCY",
  TOGGLE_HIDDEN_CART_MODAL: "TOGGLE_HIDDEN_CART_MODAL",
  TOGGLE_HIDDEN_CURRENCY_MODAL: "TOGGLE_HIDDEN_CURRENCY_MODAL",
  CLOSE_CURRENCY_MODAL: "CLOSE_CURRENCY_MODAL",
  CLOSE_CART_MODAL: "CLOSE_CART_MODAL",
  ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
  REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",
};

export default CartActionTypes;
